/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estudiantesmejorado;
import java.util.LinkedList;
/**
 *
 * @author polip
 */
public class Ingreso_Datos extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso_Datos
     */
    public Ingreso_Datos() {
        initComponents();
        Lista=new LinkedList<Estudiante>();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        CedulaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NombreTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CarreraTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SemestreTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CBuscada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BuscarPBT = new javax.swing.JButton();
        BuscarEBT = new javax.swing.JButton();
        ResultadoLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula");

        CedulaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTFActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        NombreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTFActionPerformed(evt);
            }
        });

        jLabel3.setText("Carrera");

        CarreraTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreraTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Semestre");

        SemestreTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemestreTFActionPerformed(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CBuscada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBuscadaActionPerformed(evt);
            }
        });

        jLabel5.setText("Cedula Buscada");

        BuscarPBT.setText("Buscar Pos");
        BuscarPBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPBTActionPerformed(evt);
            }
        });

        BuscarEBT.setText("Buscar Est");
        BuscarEBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEBTActionPerformed(evt);
            }
        });

        ResultadoLB.setText("RESULTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SemestreTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreTF)
                                .addComponent(CarreraTF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResultadoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(CBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BuscarPBT)
                                    .addGap(27, 27, 27)
                                    .addComponent(BuscarEBT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarEBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarPBT))
                .addGap(34, 34, 34)
                .addComponent(ResultadoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CedulaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CarreraTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SemestreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CedulaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTFActionPerformed

    private void NombreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTFActionPerformed

    private void CarreraTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreraTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreraTFActionPerformed

    private void SemestreTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemestreTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemestreTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Se ingreso "+new Estudiante(CedulaTF.getText(),CarreraTF.getText(),NombreTF.getText(),SemestreTF.getText()).toString());
        Lista.add(new Estudiante(CedulaTF.getText(),CarreraTF.getText(),NombreTF.getText(),SemestreTF.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CBuscadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBuscadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBuscadaActionPerformed

    private void BuscarPBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPBTActionPerformed
        // TODO add your handling code here:
        ResultadoLB.setText(Buscar_Posicion(CBuscada.getText()));
        
    }//GEN-LAST:event_BuscarPBTActionPerformed

    private void BuscarEBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEBTActionPerformed
        // TODO add your handling code here:
        ResultadoLB.setText(Buscar_Estudiante(CBuscada.getText()).toString());
    }//GEN-LAST:event_BuscarEBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Datos().setVisible(true);
            }
        });
    }
    public String Buscar_Posicion( String Cedula) 
	{
            System.out.println(Lista.size());
		for (int i=0; i < Lista.size();i++)
		{
                        System.out.println("Se comparo "+Lista.get(i).getCedula()+" con "+Cedula);
			if (Cedula.equals(Lista.get(i).getCedula()))
			{
                                
				return "Esta en la posicion "+(i+1);
			}
		}
		return "No existe";
	}
	/**Creacion de funcion no miembro que nos permite Buscar un estudiante y retorna el objeto estudiante*/
	public Estudiante Buscar_Estudiante ( String Cedula)
	{
		for (int i=0; i < Lista.size();i++)
		{
			 if (Lista.get(i).getCedula().equals(Cedula))
			{
				return Lista.get(i);
			}	
		}
		return null;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarEBT;
    private javax.swing.JButton BuscarPBT;
    private javax.swing.JTextField CBuscada;
    private javax.swing.JTextField CarreraTF;
    private javax.swing.JTextField CedulaTF;
    private javax.swing.JTextField NombreTF;
    private javax.swing.JLabel ResultadoLB;
    private javax.swing.JTextField SemestreTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
    //Mis propias variables
     private LinkedList<Estudiante> Lista;
}
