SELECT * FROM DBA_ROLES;
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--Creacion y eliminacion total de roles
CREATE ROLE nombre_rol;
DROP ROLE nombre_rol;

CREATE ROLE Bodeguero;
CREATE ROLE facturador;
CREATE ROLE Compras;

GRANT permiso,permiso ON nombre_tabla TO nombre_rol;
GRANT SELECT ON EMPRESA TO BODEGUERO;
GRANT SELECT,INSERT,UPDATE,DELETE ON BODEGA TO BODEGUERO;
GRANT SELECT ON PROVEEDOR TO BODEGUERO;
GRANT SELECT,INSERT,UPDATE,DELETE ON CATEGORIA TO BODEGUERO;
GRANT SELECT,INSERT,UPDATE,DELETE ON PRODUCTO TO BODEGUERO;
GRANT SELECT ON PROVINCIA TO BODEGUERO;
GRANT SELECT ON SUCURSAL TO BODEGUERO;

GRANT SELECT ON EMPRESA TO FACTURADOR;
GRANT SELECT ON BODEGA TO FACTURADOR;
GRANT SELECT,INSERT ON CLIENTE TO FACTURADOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON FACTURA TO FACTURADOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON DETALLE_FACTURA TO FACTURADOR;
GRANT SELECT,INSERT,UPDATE,DELETE ON FORM_PAG_FACTURA TO FACTURADOR;
GRANT SELECT ON CATEGORIA TO FACTURADOR;
GRANT SELECT ON CIUDAD TO FACTURADOR;
GRANT SELECT ON PROVINCIA TO FACTURADOR;
GRANT SELECT ON FORMA_PAGO TO FACTURADOR;
GRANT SELECT ON SUCURSAL TO FACTURADOR;

GRANT SELECT ON EMPRESA TO COMPRAS;
GRANT SELECT ON BODEGA TO COMPRAS;
GRANT SELECT ON PRODUCTO TO COMPRAS;
GRANT SELECT,INSERT,UPDATE,DELETE ON PROVEEDOR TO COMPRAS;
GRANT SELECT ON CATEGORIA TO COMPRAS;
GRANT SELECT ON CIUDAD TO COMPRAS;
GRANT SELECT ON PROVINCIA TO COMPRAS;
GRANT SELECT ON SUCURSAL TO COMPRAS;

REVOKE nombre_permiso ON nombre_tabla FROM nombre_rol;
GRANT SELECT ON FACTURA TO COMPRAS;
REVOKE SELECT ON FACTURA FROM COMPRAS;

SELECT * FROM DBA_USERS;

CREATE USER jpalacios
IDENTIFIED BY jpalacios
DEFAULT TABLESPACE DATOS_2024_01;
GRANT CONNECT,RESOURCE, COMPRAS TO jpalacios;

CREATE USER llopez
IDENTIFIED BY llopez
DEFAULT TABLESPACE DATOS_2024_01;
GRANT CONNECT,RESOURCE, facturador TO llopez;

CREATE USER palmeida
IDENTIFIED BY palmeida
DEFAULT TABLESPACE DATOS_2024_01;
GRANT CONNECT,RESOURCE, bodeguero TO palmeida;

SELECT * FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN('LLOPEZ','PALMEIDA','JPALACIOS')
ORDER BY GRANTEE;

--Si hago aglun cambio debo hacer commit para que otros usuarios lo vean
INSERT INTO cliente VALUES('2222222222','C-128','LUIS', 'CARDENAS', 'ejarellano@puce.edu.ec', '099564534', '10 DE AGOSTO Y ORELLANA','LAS CASAS');
commit;


CREATE USER usprueba
IDENTIFIED BY usprueba
DEFAULT TABLESPACE DATOS_2024_01;
select * from bodega;

ALTER USER achafla IDENTIFIED BY achafla;





