/ELECT C.CLI_CEDULA_RUC,C.CLI_NOMBRE,F.FAC_NUMERO,F.FAC_FECHA,DF.DTF_CANTIDAD
FROM CLIENTE C,FACTURA F,DETALLE_FACTURA DF
WHERE F.FAC_NUMERO=DF.FAC_NUMERO
AND C.CLI_CEDULA_RUC=F.CLI_CEDULA_RUC
AND DF.PRD_CODIGO IN'AG5'
AND F.SUC_CODIGO='S_001';
DESC CLIENTE;

--NUMERO DE PRODUCTOS DE LAS FACTURAS ENTRE EN23 Y 30 SEP 
SELECT 
FROM FACTURA F,DETALLE_FACTURA DF
WHERE F.FAC_NUMERO=DF.FAC_NUMERO
AND F.FECHA BETWEN '01/01/2023' AND '30/09/2023';
DESC FORMA_PAGO;
--Todos los clientes que ha vomprado cd4 con tarjeta de crido
SELECT C.CLI_CEDULA_RUC AS CEDULA, C.CLI_NOMBRE AS NOMBRE ,F.FAC_NUMERO AS NUM_FACTURA, F.FAC_FECHA AS FECHA
FROM CLIENTE C, FACTURA F,DETALLE_FACTURA DF,FORMA_PAGO FP,FORM_PAG_FACTURA FPF
WHERE F.CLI_CEDULA_RUC=C.CLI_CEDULA_RUC
AND F.FAC_NUMERO=DF.FAC_NUMERO
AND FP.FRP_CODIGO=FPF.FRP_CODIGO
AND FPF.FAC_NUMERO=F.FAC_NUMERO
AND DF.PRD_CODIGO IN 'CD4'
AND FP.FRP_DESCRIPCION IN 'TARJETA CREDITO';

--'' ES NULO, SI METO ESPACIOS VACIOS NO ES NULL
INSERT INTO cliente VALUES('1111111111','C-128','SEBAS XACOME', 'DS DS','rcmendez@puce.edu.ec','0978452132','', 'QUIMIAG');

SELECT * FROM CLIENTE
WHERE CLI_DIRECCION IS NULL;

SELECT * FROM FACTURA WHERE TO_NUMBER( TO_CHAR(FAC_FECHA,'yyyy'))IN 2023;

--todas las ordenes de compra de febrero en las cuales se ha pedido AG7
DESC ORDEN_COMPRA;
DESC DETALLE_ORD_COM;
SELECT * 
FROM ORDEN_COMPRA OC,DETALLE_ORD_COM DOC
WHERE OC.ORD_NUMERO=DOC.ORD_NUMERO
AND TO_NUMBER( TO_CHAR(ord_FECHA,'mm'))IN 02
AND DOC.PRD_CODIGO IN 'AG7';
--Descripcion de la bodega/Numero de orden /Nombre del proveedor/desc del producto/cantidad en unidades/ precio/total de febereo
DESC PROVEEDOR;
DESC PRODUCTO;
desc orden_compra;
desc detalle_ord_com;
DESC PRODUCTO_PROOVEDOR;
DESC BODEGA;
DESC UNIDAD_ALTERNATIVA;
SELECT * FROM PROVEEDOR;
SELECT B.BOD_DESCRIPCION AS DESCRIPCION_BODEGA,OC.ORD_NUMERO AS ORDEN_NUMERO,PRV.PVE_DESCRIPCION AS NOMBRE_PROOVEDOR,
P.PRD_DESCRIPCION AS DESCRIPCION_PRODUCTO
FROM ORDEN_COMPRA OC,DETALLE_ORD_COM DOC,PROVEEDOR PRV,BODEGA B,PRODUCTO P,UNIDAD_MEDIDA UM,UNIDAD_ALTERNATIVA UA
WHERE OC.ORD_NUMERO=DOC.ORD_NUMERO
AND PRV.PVE_CEDULA_RUC=OC.PVE_CEDULA_RUC
AND B.BOD_CODIGO=OC.BOD_CODIGO
AND DOC.PRD_CODIGO=P.PRD_CODIGO
AND UM.UNM_CODIGO=UA.UNM_CODIGO
AND UA.PRD_CODIGO=P.PRD_CODIGO;


SELECT at1,at2,..., FROM TABLA
INNER JOIN TABLE TABLA2
ON at1=at2
WHERE CONDICION
ORDER BY atr;

SELECT at1,at2,..., FROM TABLA
left JOIN TABLE TABLA2
ON at1=at2
WHERE CONDICION
ORDER BY atr;

desc factura;
--inner join me da la interseccion
select c.cli_nombre,f.fac_numero,f.fac_monto from cliente c
INNER JOIN factura f
ON c.cli_cedula_ruc=f.cli_cedula_ruc
ORDER BY fac_numero ;
--left join me da el conjunta de la izquierda
select c.cli_nombre,f.fac_numero,f.fac_monto from cliente c
LEFT JOIN factura f
ON c.cli_cedula_ruc=f.cli_cedula_ruc
ORDER BY fac_numero ;
--clientes que no facturar