INSERT INTO UNIDAD_MEDIDA VALUES('LT','litros');
INSERT INTO UNIDAD_MEDIDA VALUES('OZ','Onzas');
INSERT INTO UNIDAD_MEDIDA VALUES('KG','Kilogramo');
INSERT INTO UNIDAD_MEDIDA VALUES('GR','GRAMO');
INSERT INTO UNIDAD_MEDIDA VALUES('U','Unidad');
SELECT * FROM UNIDAD_MEDIDA;