SELECT * FROM tab;
DESCRIBE bodega;
DESC empresa;
ALTER TABLE empresa MODIFY(emp_iva NUMBER(4,2));
INSERT INTO empresa VALUES('1735456724','IMPORTADORA XYZ','Av. 10 de Agosto 1070 y Nacione Unidas','123456','impor@hotmail.com','15','099234','Jorge Luis Patiño','1','2',0.1);


INSERT INTO categorias VALUES('01','LIMPIEZA');
INSERT INTO categorias VALUES('02','FRUTAS Y VERDURAS');
INSERT INTO categorias VALUES('03','LICORES');
INSERT INTO categorias VALUES('04','ENLATADOS');
INSERT INTO categorias VALUES('10','GRANOS SECOS');

INSERT INTO categorias VALUES('05','ASEO PERSONAL');
INSERT INTO categorias VALUES('06','HOGAR');
INSERT INTO categorias VALUES('07','ROPA');
INSERT INTO categorias VALUES('08','CALSADO');
INSERT INTO categorias VALUES('09','JUGUETES');

INSERT INTO producto VALUES('CD1','01','DETERGENTE DEJA',18.50,15.20,7,'12345678','S');
INSERT INTO producto VALUES('CD2','01','DESINFECTANTE KLM',10.50,8.20,7,'12345679','S');
INSERT INTO producto VALUES('CD3','01','CLORO',5.0,4.50,7,'12345680','S');
INSERT INTO producto VALUES('CD10','02','LECHUGA CRESPA',0.75,0.60,7,'201524','N');
INSERT INTO producto VALUES('CD11','02','PAPA CHOLA',0.45,0.30,7,'201530','N');
INSERT INTO producto VALUES('CD30','03','VINO TINTO CONCHA Y TORO',15.75,12.60,7,'507024','S');

INSERT INTO provincia VALUES('01','Azuay');
INSERT INTO provincia VALUES('02','Bolívar'); 
INSERT INTO provincia VALUES('03','Cañar');  
INSERT INTO provincia VALUES('04','Carchi'); 
INSERT INTO provincia VALUES('05','Cotopaxi'); 
INSERT INTO provincia VALUES('06','Chimborazo'); 
INSERT INTO provincia VALUES('07','El Oro'); 
INSERT INTO provincia VALUES('08','Esmeraldas'); 
INSERT INTO provincia VALUES('09','Guayas'); 
INSERT INTO provincia VALUES('10','Imbabura'); 
INSERT INTO provincia VALUES('11','Loja'); 
INSERT INTO provincia VALUES('12','Los Ríos'); 
INSERT INTO provincia VALUES('13','Manabí'); 
INSERT INTO provincia VALUES('14','Morona Santiago'); 
INSERT INTO provincia VALUES('15','Napo'); 
INSERT INTO provincia VALUES('16','Pastaza'); 
INSERT INTO provincia VALUES('17', 'Pichincha'); 
INSERT INTO provincia VALUES('18', 'Tungurahua'); 
INSERT INTO provincia VALUES('19', 'Zamora Chinchipe'); 
INSERT INTO provincia VALUES('20', 'Galápagos'); 
INSERT INTO provincia VALUES('21', 'Sucumbíos'); 
INSERT INTO provincia VALUES('22', 'Orellana'); 
INSERT INTO provincia VALUES('23', 'SantoDomingo'); 
INSERT INTO provincia VALUES('24', 'Santa Elena');


INSERT INTO ciudad VALUES('C-1', '01', 'Cuenca');
INSERT INTO ciudad VALUES('C-2', '01', 'Gualaceo');
INSERT INTO ciudad VALUES('C-3', '01', 'Paute');
INSERT INTO ciudad VALUES('C-4', '01', 'Sigsig');
INSERT INTO ciudad VALUES('C-5', '01', 'Girón');
INSERT INTO ciudad VALUES('C-6', '01', 'San Fernando');
INSERT INTO ciudad VALUES('C-7', '01', 'Santa Isabel');
INSERT INTO ciudad VALUES('C-8', '01', 'Pucará');
INSERT INTO ciudad VALUES('C-9', '01', 'Nabón');
INSERT INTO ciudad VALUES('C-10', '20', 'Isabela');
INSERT INTO ciudad VALUES('C-11', '20', 'Santa Cruz');
INSERT INTO ciudad VALUES('C-12', '20', 'Puerto BM');
INSERT INTO ciudad VALUES('C-13', '20', 'Puerto Ayora');
INSERT INTO ciudad VALUES('C-14', '03', 'Cañar');
INSERT INTO ciudad VALUES('C-15', '03', 'Biblián');
INSERT INTO ciudad VALUES('C-16', '03', 'Azogue');
INSERT INTO ciudad VALUES('C-17', '03', 'La Troncal');
INSERT INTO ciudad VALUES('C-18', '02', 'Guaranda');
INSERT INTO ciudad VALUES('C-19', '02', 'San Miguel');
INSERT INTO ciudad VALUES('C-20', '02', 'Caluma');
INSERT INTO ciudad VALUES('C-21', '02', 'Chillanes');
INSERT INTO ciudad VALUES('C-22', '02', 'Echeandía');
INSERT INTO ciudad VALUES('C-23', '02', 'Chimbo');
INSERT INTO ciudad VALUES('C-24', '02', 'La Asunción');
INSERT INTO ciudad VALUES('C-25', '02', 'La Magdalena');
INSERT INTO ciudad VALUES('C-26', '04', 'Mira');
INSERT INTO ciudad VALUES('C-27', '04', 'Bolívar');
INSERT INTO ciudad VALUES('C-28', '04', 'Tulcán');
INSERT INTO ciudad VALUES('C-29', '04', 'El Angel');
INSERT INTO ciudad VALUES('C-30', '04', 'Huaca');
INSERT INTO ciudad VALUES('C-31', '04', 'Julio Andrade');
INSERT INTO ciudad VALUES('C-32', '04', 'La Paz');
INSERT INTO ciudad VALUES('C-33', '04', 'San Gabriel');
INSERT INTO ciudad VALUES('C-34', '06', 'Riobamba');
INSERT INTO ciudad VALUES('C-35', '06', 'Guano');
INSERT INTO ciudad VALUES('C-36', '06', 'Chambo');
INSERT INTO ciudad VALUES('C-37', '06', 'Colta');
INSERT INTO ciudad VALUES('C-38', '06', 'Penipe');
INSERT INTO ciudad VALUES('C-39', '06', 'Guamote');
INSERT INTO ciudad VALUES('C-40', '06', 'Pallatanga');
INSERT INTO ciudad VALUES('C-41', '06', 'Alausí');
INSERT INTO ciudad VALUES('C-42', '06', 'Chunchi');
INSERT INTO ciudad VALUES('C-43', '06', 'Cumandá');
INSERT INTO ciudad VALUES('C-44', '06', 'Cajabamba');
INSERT INTO ciudad VALUES('C-45', '06', 'Huigra');
INSERT INTO ciudad VALUES('C-46', '06', 'San Andrés');
INSERT INTO ciudad VALUES('C-47', '06', 'San Juan');
INSERT INTO ciudad VALUES('C-48', '05', 'Saquisilí');
INSERT INTO ciudad VALUES('C-49', '05', 'Latacunga');
INSERT INTO ciudad VALUES('C-50', '05', 'Pujilí');
INSERT INTO ciudad VALUES('C-51', '05', 'Salcedo');
INSERT INTO ciudad VALUES('C-52', '05', 'Sigchos');
INSERT INTO ciudad VALUES('C-53', '05', 'La Maná');
INSERT INTO ciudad VALUES('C-54', '05', 'Chantillin');
INSERT INTO ciudad VALUES('C-55', '05', 'El Corazón');
INSERT INTO ciudad VALUES('C-56', '05', 'Guaytacama');
INSERT INTO ciudad VALUES('C-57', '05', 'Lasso');
INSERT INTO ciudad VALUES('C-58', '05', 'Pastocalle');
INSERT INTO ciudad VALUES('C-59', '05', 'Poalo');
INSERT INTO ciudad VALUES('C-60', '05', 'Tanicuchi');
INSERT INTO ciudad VALUES('C-61', '05', 'Toacaso');
INSERT INTO ciudad VALUES('C-62', '05', 'Mulalo');
INSERT INTO ciudad VALUES('C-63', '07', 'El Guabo');
INSERT INTO ciudad VALUES('C-64', '07', 'Huaquillas');
INSERT INTO ciudad VALUES('C-65', '07', 'Machala');
INSERT INTO ciudad VALUES('C-66', '07', 'Pasaje');
INSERT INTO ciudad VALUES('C-67', '07', 'Piñas');
INSERT INTO ciudad VALUES('C-68', '07', 'Puerto Bolivar');
INSERT INTO ciudad VALUES('C-69', '07', 'Santa Rosa');
INSERT INTO ciudad VALUES('C-70', '07', 'Zaruma');
INSERT INTO ciudad VALUES('C-71', '07', 'Portovelo');
INSERT INTO ciudad VALUES('C-72', '07', 'Arenillas');
INSERT INTO ciudad VALUES('C-73', '07', 'Atahualpa');
INSERT INTO ciudad VALUES('C-74', '07', 'Balsas');
INSERT INTO ciudad VALUES('C-75', '07', 'Chilla');
INSERT INTO ciudad VALUES('C-76', '07', 'Marcabeli');
INSERT INTO ciudad VALUES('C-77', '08', 'Esmeraldas');
INSERT INTO ciudad VALUES('C-78', '09', 'Guayaquil');
INSERT INTO ciudad VALUES('C-79', '09', 'Daule');
INSERT INTO ciudad VALUES('C-80', '09', 'Duran');
INSERT INTO ciudad VALUES('C-81', '09', 'El Empalme');
INSERT INTO ciudad VALUES('C-82', '24', 'Santa Elena');
INSERT INTO ciudad VALUES('C-83', '24', 'La Libertad');
INSERT INTO ciudad VALUES('C-84', '24', 'Salinas');
INSERT INTO ciudad VALUES('C-85', '11', 'Loja');
INSERT INTO ciudad VALUES('C-86', '11', 'Macara');
INSERT INTO ciudad VALUES('C-87', '11', 'Catamayo');
INSERT INTO ciudad VALUES('C-88', '11', 'Cariamanga');
INSERT INTO ciudad VALUES('C-89', '11', 'Celica');
INSERT INTO ciudad VALUES('C-90', '14', 'Macas');
INSERT INTO ciudad VALUES('C-91', '14', 'Gualaquiza');
INSERT INTO ciudad VALUES('C-92', '14', 'Limon Indanza');
INSERT INTO ciudad VALUES('C-93', '14', 'Santiago');
INSERT INTO ciudad VALUES('C-94', '14', 'Sucua');
INSERT INTO ciudad VALUES('C-95', '10', 'Ibarra');
INSERT INTO ciudad VALUES('C-96', '10', 'Ambuqui');
INSERT INTO ciudad VALUES('C-97', '10', 'Atuntaqui');
INSERT INTO ciudad VALUES('C-98', '10', 'Cotacachi');
INSERT INTO ciudad VALUES('C-99', '10', 'Otavalo');
INSERT INTO ciudad VALUES('C-100', '12', 'Ibarra');
INSERT INTO ciudad VALUES('C-101', '12', 'Ambuqui');
INSERT INTO ciudad VALUES('C-102', '12', 'Atuntaqui');
INSERT INTO ciudad VALUES('C-103', '12', 'Cotacachi');
INSERT INTO ciudad VALUES('C-104', '12', 'Otavalo');
INSERT INTO ciudad VALUES('C-105', '13', 'Portoviejo');
INSERT INTO ciudad VALUES('C-106', '13', 'Bahia De Caraquez');
INSERT INTO ciudad VALUES('C-107', '13', 'Chone');
INSERT INTO ciudad VALUES('C-108', '13', 'El Carmen');
INSERT INTO ciudad VALUES('C-109', '13', 'Jipijapa');
INSERT INTO ciudad VALUES('C-110', '15', 'Tena');
INSERT INTO ciudad VALUES('C-111', '15', 'Archidona');
INSERT INTO ciudad VALUES('C-112', '15', 'Baeza');
INSERT INTO ciudad VALUES('C-113', '15', 'El Chaco');
INSERT INTO ciudad VALUES('C-114', '15', 'Carlos Julio Aroseme');
INSERT INTO ciudad VALUES('C-115', '22', 'Francisco De Orellan');
INSERT INTO ciudad VALUES('C-116', '22', 'La Joya De Los Sacha');
INSERT INTO ciudad VALUES('C-117', '22', 'Loreto');
INSERT INTO ciudad VALUES('C-118', '22', 'Nuevo Rocafuerte');
INSERT INTO ciudad VALUES('C-119', '16', 'Puyo');
INSERT INTO ciudad VALUES('C-120', '16', 'Mera');
INSERT INTO ciudad VALUES('C-121', '16', 'Palora');
INSERT INTO ciudad VALUES('C-122', '16', 'Shell');
INSERT INTO ciudad VALUES('C-123', '16', 'Arajuno');
INSERT INTO ciudad VALUES('C-124', '23', 'Santo D');
INSERT INTO ciudad VALUES('C-125', '23', 'Alluriquin');
INSERT INTO ciudad VALUES('C-126', '23', 'Luz De América');
INSERT INTO ciudad VALUES('C-127', '23', 'Valle Hermoso');
INSERT INTO ciudad VALUES('C-128', '17', 'Quito');
INSERT INTO ciudad VALUES('C-129', '17', 'Cayambe');
INSERT INTO ciudad VALUES('C-130', '17', 'Conocoto');
INSERT INTO ciudad VALUES('C-131', '17', 'Cumbaya');
INSERT INTO ciudad VALUES('C-132', '17', 'Machachi');
INSERT INTO ciudad VALUES('C-133', '21', 'Nueva Loja');
INSERT INTO ciudad VALUES('C-134', '21', 'Gonzalo Pizarro');
INSERT INTO ciudad VALUES('C-135', '21', 'Putumayo');
INSERT INTO ciudad VALUES('C-136', '21', 'Shushufindi');
INSERT INTO ciudad VALUES('C-137', '21', 'Sucumbios');
INSERT INTO ciudad VALUES('C-138', '18', 'Ambato');
INSERT INTO ciudad VALUES('C-139', '18', 'Baños');
INSERT INTO ciudad VALUES('C-140', '18', 'Cevallos');
INSERT INTO ciudad VALUES('C-141', '18', 'Izamba');
INSERT INTO ciudad VALUES('C-142', '18', 'Mocha');
INSERT INTO ciudad VALUES('C-143', '19', 'Zamora');
INSERT INTO ciudad VALUES('C-144', '19', 'Chinchipe');
INSERT INTO ciudad VALUES('C-145', '19', 'Nangaritza');
INSERT INTO ciudad VALUES('C-146', '19', 'Yacuambi');
INSERT INTO ciudad VALUES('C-147', '19', 'Yantzaza');

SELECT * FROM sucursal;


INSERT INTO sucursal VALUES('S_001', 'C-128', 'QUITO NORTE', 'AV DE LA PRENSA 1070', '022564535','LUIS ALBERTO MEDINA');
INSERT INTO sucursal VALUES('S_002', 'C-128', 'QUITO SUR', 'AV MALDONADO 20-54', '022348923','JORGE LÓPEZ');
INSERT INTO sucursal VALUES('S_003', 'C-78', 'GUAYAQUIL NORTE', 'AV DE LA PRENSA', '022564535','CARLOS CÁRDENAS');
INSERT INTO sucursal VALUES('S_004', 'C-78', 'GUAYAQUIL SUR', 'LEÓN FEBRESCORDERO', '022348923','ARTURO CAJAS');
INSERT INTO sucursal VALUES('S_005', 'C-1', 'CUENCA NORTE', 'LA LARGA N-124', '022348923','LAURA PÉREZ');

INSERT INTO bodega VALUES('BOD_01', 'S_001','BODEGA PRODUCTO Q1','PATRICIO PARAMO');
INSERT INTO bodega VALUES('BOD_02', 'S_002','BODEGA PRODUCTO Q2','MANUEL PAREDES');
INSERT INTO bodega VALUES('BOD_03', 'S_003','BODEGA PRODUCTO G','ROCIO PERALTA');
INSERT INTO bodega VALUES('BOD_04', 'S_004','BODEGA PRODUCTO G2','CRISTIAN GALARZA');
INSERT INTO bodega VALUES('BOD_05', 'S_005','BODEGA PRODUCTO G3','MARIA ORDOÑEZ');
COMMIT;