DESC FORMA_PAGO;

INSERT INTO FORMA_PAGO VALUES('TRS','TRANSACCION INTERBANCARIA');
INSERT INTO FORMA_PAGO VALUES('EFC','EFECTIVO');
INSERT INTO FORMA_PAGO VALUES('CRD','TARJETA DE CREDITO');
INSERT INTO FORMA_PAGO VALUES('CHQ','CHEQUE');
INSERT INTO FORMA_PAGO VALUES('DEB','TARJETA DE DEBITO');