DESC DETALLE_ORDEN_COMPRA;
DESC ORDEN_COMPRA;
DESC KARDEX;
SELECT * FROM PRODUCTO;
--EN TOTAL VA LA SUMA DE LOS PRODUCTOS DE DETALLES
--ME TOCA HACER ESTO MANUALMENTE
--POR LO MENOS 1 ORDEN DE COMPRA POR SUCURSAL
INSERT INTO ORDEN_COMPRA VALUES('OC00N','BOD00N','PRV00N',F1,F2,F3,TOTAL);
INSERT INTO DETALLE_ORDEN_COMPRA VALUES ('OC00N','');
INSERT INTO DETALLE_ORDEN_COMPRA VALUES ('OC00N','');